version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: docker-rsi
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DATABASE: acara_rsi
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  postgres_data: